AWSTemplateFormatVersion: '2010-09-09'

Description: >
  CloudFormation template to create an EC2 instance.

Parameters:

  InstanceType:
    Type: String
    Description: EC2 Instance Type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 Key Pair

  AMIId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Machine Image (AMI) ID

Resources:

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName

      Tags:
        - Key: Name
          Value: MyFirstCloudFormationEC2

Outputs:

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: Public IP Address
    Value: !GetAtt MyEC2Instance.PublicIp

  PublicDNS:
    Description: Public DNS Name
    Value: !GetAtt MyEC2Instance.PublicDnsName

  AvailabilityZone:
    Description: Availability Zone
    Value: !GetAtt MyEC2Instance.AvailabilityZone